export const RECEIVE_SPEAKERS = '[SONOS] RECEIVE_SPEAKERS'
export const REQUEST_SPEAKERS = '[SONOS] REQUEST_SPEAKERS'

export const PLAY_ON_SPEAKER = '[SONOS] PLAY_ON_SPEAKER'
export const ADD_TO_SPEAKER_QUEUE = '[SONOS] ADD_TO_SPEAKER_QUEUE'
